// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dir is the predicate function for dir builders.
type Dir func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// SyncTask is the predicate function for synctask builders.
type SyncTask func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
