// Code generated by ent, DO NOT EDIT.

package file

const (
	// Label holds the string label denoting the file type in the database.
	Label = "file"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSyncID holds the string denoting the sync_id field in the database.
	FieldSyncID = "sync_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldParentDirID holds the string denoting the parent_dir_id field in the database.
	FieldParentDirID = "parent_dir_id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldModTime holds the string denoting the mod_time field in the database.
	FieldModTime = "mod_time"
	// Table holds the table name of the file in the database.
	Table = "files"
)

// Columns holds all SQL columns for file fields.
var Columns = []string{
	FieldID,
	FieldSyncID,
	FieldName,
	FieldParentDirID,
	FieldLevel,
	FieldHash,
	FieldSize,
	FieldDeleted,
	FieldCreateTime,
	FieldModTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
