// Code generated by ent, DO NOT EDIT.

package dir

const (
	// Label holds the string label denoting the dir type in the database.
	Label = "dir"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSyncID holds the string denoting the sync_id field in the database.
	FieldSyncID = "sync_id"
	// FieldDir holds the string denoting the dir field in the database.
	FieldDir = "dir"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldModTime holds the string denoting the mod_time field in the database.
	FieldModTime = "mod_time"
	// Table holds the table name of the dir in the database.
	Table = "dirs"
)

// Columns holds all SQL columns for dir fields.
var Columns = []string{
	FieldID,
	FieldSyncID,
	FieldDir,
	FieldLevel,
	FieldDeleted,
	FieldCreateTime,
	FieldModTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
