// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"fsm_client/pkg/ent/dir"
	"fsm_client/pkg/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DirUpdate is the builder for updating Dir entities.
type DirUpdate struct {
	config
	hooks    []Hook
	mutation *DirMutation
}

// Where appends a list predicates to the DirUpdate builder.
func (du *DirUpdate) Where(ps ...predicate.Dir) *DirUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetSyncID sets the "sync_id" field.
func (du *DirUpdate) SetSyncID(s string) *DirUpdate {
	du.mutation.SetSyncID(s)
	return du
}

// SetDir sets the "dir" field.
func (du *DirUpdate) SetDir(s string) *DirUpdate {
	du.mutation.SetDir(s)
	return du
}

// SetLevel sets the "level" field.
func (du *DirUpdate) SetLevel(u uint64) *DirUpdate {
	du.mutation.ResetLevel()
	du.mutation.SetLevel(u)
	return du
}

// AddLevel adds u to the "level" field.
func (du *DirUpdate) AddLevel(u int64) *DirUpdate {
	du.mutation.AddLevel(u)
	return du
}

// SetDeleted sets the "deleted" field.
func (du *DirUpdate) SetDeleted(b bool) *DirUpdate {
	du.mutation.SetDeleted(b)
	return du
}

// SetCreateTime sets the "create_time" field.
func (du *DirUpdate) SetCreateTime(t time.Time) *DirUpdate {
	du.mutation.SetCreateTime(t)
	return du
}

// SetModTime sets the "mod_time" field.
func (du *DirUpdate) SetModTime(t time.Time) *DirUpdate {
	du.mutation.SetModTime(t)
	return du
}

// Mutation returns the DirMutation object of the builder.
func (du *DirUpdate) Mutation() *DirMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DirUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, DirMutation](ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DirUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DirUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DirUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DirUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dir.Table, dir.Columns, sqlgraph.NewFieldSpec(dir.FieldID, field.TypeString))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.SyncID(); ok {
		_spec.SetField(dir.FieldSyncID, field.TypeString, value)
	}
	if value, ok := du.mutation.Dir(); ok {
		_spec.SetField(dir.FieldDir, field.TypeString, value)
	}
	if value, ok := du.mutation.Level(); ok {
		_spec.SetField(dir.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := du.mutation.AddedLevel(); ok {
		_spec.AddField(dir.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := du.mutation.Deleted(); ok {
		_spec.SetField(dir.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := du.mutation.CreateTime(); ok {
		_spec.SetField(dir.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := du.mutation.ModTime(); ok {
		_spec.SetField(dir.FieldModTime, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dir.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DirUpdateOne is the builder for updating a single Dir entity.
type DirUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DirMutation
}

// SetSyncID sets the "sync_id" field.
func (duo *DirUpdateOne) SetSyncID(s string) *DirUpdateOne {
	duo.mutation.SetSyncID(s)
	return duo
}

// SetDir sets the "dir" field.
func (duo *DirUpdateOne) SetDir(s string) *DirUpdateOne {
	duo.mutation.SetDir(s)
	return duo
}

// SetLevel sets the "level" field.
func (duo *DirUpdateOne) SetLevel(u uint64) *DirUpdateOne {
	duo.mutation.ResetLevel()
	duo.mutation.SetLevel(u)
	return duo
}

// AddLevel adds u to the "level" field.
func (duo *DirUpdateOne) AddLevel(u int64) *DirUpdateOne {
	duo.mutation.AddLevel(u)
	return duo
}

// SetDeleted sets the "deleted" field.
func (duo *DirUpdateOne) SetDeleted(b bool) *DirUpdateOne {
	duo.mutation.SetDeleted(b)
	return duo
}

// SetCreateTime sets the "create_time" field.
func (duo *DirUpdateOne) SetCreateTime(t time.Time) *DirUpdateOne {
	duo.mutation.SetCreateTime(t)
	return duo
}

// SetModTime sets the "mod_time" field.
func (duo *DirUpdateOne) SetModTime(t time.Time) *DirUpdateOne {
	duo.mutation.SetModTime(t)
	return duo
}

// Mutation returns the DirMutation object of the builder.
func (duo *DirUpdateOne) Mutation() *DirMutation {
	return duo.mutation
}

// Where appends a list predicates to the DirUpdate builder.
func (duo *DirUpdateOne) Where(ps ...predicate.Dir) *DirUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DirUpdateOne) Select(field string, fields ...string) *DirUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Dir entity.
func (duo *DirUpdateOne) Save(ctx context.Context) (*Dir, error) {
	return withHooks[*Dir, DirMutation](ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DirUpdateOne) SaveX(ctx context.Context) *Dir {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DirUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DirUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DirUpdateOne) sqlSave(ctx context.Context) (_node *Dir, err error) {
	_spec := sqlgraph.NewUpdateSpec(dir.Table, dir.Columns, sqlgraph.NewFieldSpec(dir.FieldID, field.TypeString))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dir.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dir.FieldID)
		for _, f := range fields {
			if !dir.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dir.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.SyncID(); ok {
		_spec.SetField(dir.FieldSyncID, field.TypeString, value)
	}
	if value, ok := duo.mutation.Dir(); ok {
		_spec.SetField(dir.FieldDir, field.TypeString, value)
	}
	if value, ok := duo.mutation.Level(); ok {
		_spec.SetField(dir.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := duo.mutation.AddedLevel(); ok {
		_spec.AddField(dir.FieldLevel, field.TypeUint64, value)
	}
	if value, ok := duo.mutation.Deleted(); ok {
		_spec.SetField(dir.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := duo.mutation.CreateTime(); ok {
		_spec.SetField(dir.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := duo.mutation.ModTime(); ok {
		_spec.SetField(dir.FieldModTime, field.TypeTime, value)
	}
	_node = &Dir{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dir.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
