// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fsm_client/pkg/ent/predicate"
	"fsm_client/pkg/ent/synctask"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncTaskDelete is the builder for deleting a SyncTask entity.
type SyncTaskDelete struct {
	config
	hooks    []Hook
	mutation *SyncTaskMutation
}

// Where appends a list predicates to the SyncTaskDelete builder.
func (std *SyncTaskDelete) Where(ps ...predicate.SyncTask) *SyncTaskDelete {
	std.mutation.Where(ps...)
	return std
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (std *SyncTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SyncTaskMutation](ctx, std.sqlExec, std.mutation, std.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (std *SyncTaskDelete) ExecX(ctx context.Context) int {
	n, err := std.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (std *SyncTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(synctask.Table, sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeString))
	if ps := std.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, std.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	std.mutation.done = true
	return affected, err
}

// SyncTaskDeleteOne is the builder for deleting a single SyncTask entity.
type SyncTaskDeleteOne struct {
	std *SyncTaskDelete
}

// Where appends a list predicates to the SyncTaskDelete builder.
func (stdo *SyncTaskDeleteOne) Where(ps ...predicate.SyncTask) *SyncTaskDeleteOne {
	stdo.std.mutation.Where(ps...)
	return stdo
}

// Exec executes the deletion query.
func (stdo *SyncTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := stdo.std.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{synctask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (stdo *SyncTaskDeleteOne) ExecX(ctx context.Context) {
	if err := stdo.Exec(ctx); err != nil {
		panic(err)
	}
}
