// Code generated by ent, DO NOT EDIT.

package synctask

import (
	"fsm_client/pkg/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldUserID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldType, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldName, v))
}

// RootDir applies equality check predicate on the "root_dir" field. It's identical to RootDirEQ.
func RootDir(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldRootDir, v))
}

// Ignore applies equality check predicate on the "ignore" field. It's identical to IgnoreEQ.
func Ignore(v bool) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldIgnore, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldCreateTime, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldStatus, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContainsFold(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContainsFold(FieldType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContainsFold(FieldName, v))
}

// RootDirEQ applies the EQ predicate on the "root_dir" field.
func RootDirEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldRootDir, v))
}

// RootDirNEQ applies the NEQ predicate on the "root_dir" field.
func RootDirNEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldRootDir, v))
}

// RootDirIn applies the In predicate on the "root_dir" field.
func RootDirIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldRootDir, vs...))
}

// RootDirNotIn applies the NotIn predicate on the "root_dir" field.
func RootDirNotIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldRootDir, vs...))
}

// RootDirGT applies the GT predicate on the "root_dir" field.
func RootDirGT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldRootDir, v))
}

// RootDirGTE applies the GTE predicate on the "root_dir" field.
func RootDirGTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldRootDir, v))
}

// RootDirLT applies the LT predicate on the "root_dir" field.
func RootDirLT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldRootDir, v))
}

// RootDirLTE applies the LTE predicate on the "root_dir" field.
func RootDirLTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldRootDir, v))
}

// RootDirContains applies the Contains predicate on the "root_dir" field.
func RootDirContains(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContains(FieldRootDir, v))
}

// RootDirHasPrefix applies the HasPrefix predicate on the "root_dir" field.
func RootDirHasPrefix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasPrefix(FieldRootDir, v))
}

// RootDirHasSuffix applies the HasSuffix predicate on the "root_dir" field.
func RootDirHasSuffix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasSuffix(FieldRootDir, v))
}

// RootDirEqualFold applies the EqualFold predicate on the "root_dir" field.
func RootDirEqualFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEqualFold(FieldRootDir, v))
}

// RootDirContainsFold applies the ContainsFold predicate on the "root_dir" field.
func RootDirContainsFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContainsFold(FieldRootDir, v))
}

// IgnoreEQ applies the EQ predicate on the "ignore" field.
func IgnoreEQ(v bool) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldIgnore, v))
}

// IgnoreNEQ applies the NEQ predicate on the "ignore" field.
func IgnoreNEQ(v bool) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldIgnore, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v int64) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldCreateTime, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncTask) predicate.SyncTask {
	return predicate.SyncTask(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncTask) predicate.SyncTask {
	return predicate.SyncTask(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncTask) predicate.SyncTask {
	return predicate.SyncTask(func(s *sql.Selector) {
		p(s.Not())
	})
}
